version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  post_build:
    commands:
      - mvn package
      - mv target/awstraining-eb ./
      
artifacts:
  files:
    - awstraining-eb/**/*
  discard-paths: yes