version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
    - echo In the pre_build phase...
  build:
    commands:
    - echo Build started on 
  post_build:
    commands:
    - echo Build completed on 
    - mvn package
    - mv target/awstraining-eb.war awstraining-eb.war
artifacts:
  discard-paths: yes
  files:
  - target/awstraining-eb.war
  - .ebextensions/**/*
  base-directory: 'target/awstraining-eb'